name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        config:
        - {
            name: "Windows-mingw64 Debug",
            build_type: Debug,
            cxx_standard: 20,
            msystem: MINGW64,
            cc: gcc,
            cxx: g++ 
          }
          
        - {
            name: "Windows-mingw64 Release",
            build_type: Release,
            cxx_standard: 20,
            msystem: MINGW64,
            cc: gcc,
            cxx: g++ 
          }

    steps:

    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.config.msystem}}
        
    - name: Check workflow files
      run: |
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        ./actionlint -color
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        
    - name: Configure CMake
      run: >-
        cmake 
        -B ${{github.workspace}}/build 
        -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
        -D CMAKE_C_COMPILER=gcc
        -D CMAKE_CXX_COMPILER=g++
      
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config.build_type }} 

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.config.build_type }}
