name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build-type:
          - key: debug
            name: Debug

          - key: release
            name: Release
            
    steps:

    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type.key }}
    
    - name: Install Qt
    - uses: jurplel/install-qt-action@v3
    - with:
        version: '6.2.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type.key }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.build-type.key }}

